name = input("enter your name: ")
age = input("enter your age: ")
city = input("enter your city: ")
phone_number = input("enter your phone number: ")
dob = input("enter your dob (DD/MM/YYYY): ")
blood_group = input("enter your blood group: ")

print("---MY ID CARD---")
print("Name : ", name)
print("Age : ", age)
print("City : ", city)
print("Phone Number : ", phone_number)
print("Date of Birth : ", dob)
print("Blood Group : ", blood_group)